//-----------------------------------------------------------------------
// This file is autogenerated by MudBlazor.Docs.Compiler
// Any changes to this file will be overwritten on build
// <auto-generated />
//-----------------------------------------------------------------------

namespace MudBlazor.Docs.Models
{
    public static partial class DocStrings
    {
        public const string CodeInline_ChildContent = @"";

        public const string CodeInline_Code = @"";

        public const string CodeInline_SecondaryColor = @"";

        public const string CodeInline_Class = @"";

        public const string CodeInline_Tag = @"";

        public const string DocsFrame_ChildContent = @"";

        public const string DocsPage_MaxWidth = @"";

        public const string DocsPage_ChildContent = @"";

        public const string DocsPageContent_ChildContent = @"";

        public const string DocsPageHeader_Title = @"";

        public const string DocsPageHeader_SubTitle = @"";

        public const string DocsPageHeader_Keywords = @"";

        public const string DocsPageHeader_DisableApiHeader = @"";

        public const string DocsPageHeader_Description = @"";

        public const string DocsPageHeader_ChildContent = @"";

        public const string DocsPageHeader_ComponentLink = @"";

        public const string DocsPageSection_ChildContent = @"";

        public const string DocsPageSection_UserAttributes = @"";

        public const string ExtensionCard_Extension = @"";

        public const string ExtensionPage_ExtensionId = @"";

        public const string MainLayout_Body = @"";

        public const string NugetIcon_Class = @"";

        public const string NugetIcon_PackageUrl = @"";

        public const string NugetIcon_Size = @"";

        public const string QueuedContent_ChildContent = @"";

        public const string QueuedContent_RenderImmediately = @"";

        public const string SectionContent_Class = @"";

        public const string SectionContent_Style = @"";

        public const string SectionContent_DisplayGrid = @"";

        public const string SectionContent_DisplayFlex = @"";

        public const string SectionContent_FullWidth = @"";

        public const string SectionContent_DarkenBackground = @"";

        public const string SectionContent_Outlined = @"";

        public const string SectionContent_AutoMarginContent = @"";

        public const string SectionContent_FlexColumn = @"";

        public const string SectionContent_ChildContent = @"";

        public const string SectionHeader_Class = @"";

        public const string SectionHeader_Title = @"";

        public const string SectionHeader_SubTitle = @"";

        public const string SectionHeader_Description = @"";

        public const string SectionSource_Code = @"";

        public const string SectionSource_Code2 = @"";

        public const string SectionSource_ButtonTextCode1 = @"";

        public const string SectionSource_ButtonTextCode2 = @"";

        public const string SectionSource_Class = @"";

        public const string SectionSource_GitHubFolderName = @"";

        public const string SectionSource_ShowCode = @"";

        public const string SectionSource_NoToolbar = @"";

        public const string SurveyPrompt_Title = @"";

    }
}
